name: Build and Push Docker Image

on:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
      
      - name: Ecs-compose install
        run: |
            python3 -m venv ~/venv
            source ~/venv/bin/activate
            pip install pip -U
            pip install ecs-composex

      - name: Ecs-compose install
        run: |
          ecs-compose-x up -f docker-compose.yaml -f aws-compose-x.yaml -n frontend-app
